/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 23-May-2016 00:19:04
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 128
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\edas\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 128;
const int16_T B[128] = {
       18,      1,     -2,     -6,    -12,    -17,    -20,    -20,    -17,
       -9,      2,     15,     29,     39,     44,     42,     31,     11,
      -14,    -41,    -66,    -82,    -86,    -75,    -47,     -6,     42,
       91,    130,    152,    149,    118,     61,    -16,   -101,   -181,
     -239,   -262,   -241,   -173,    -64,     74,    219,    346,    430,
      449,    389,    247,     37,   -218,   -480,   -704,   -844,   -856,
     -711,   -391,     96,    725,   1450,   2209,   2932,   3551,   4002,
     4240,   4240,   4002,   3551,   2932,   2209,   1450,    725,     96,
     -391,   -711,   -856,   -844,   -704,   -480,   -218,     37,    247,
      389,    449,    430,    346,    219,     74,    -64,   -173,   -241,
     -262,   -239,   -181,   -101,    -16,     61,    118,    149,    152,
      130,     91,     42,     -6,    -47,    -75,    -86,    -82,    -66,
      -41,    -14,     11,     31,     42,     44,     39,     29,     15,
        2,     -9,    -17,    -20,    -20,    -17,    -12,     -6,     -2,
        1,     18
};
