/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 13-Jun-2016 07:06:00
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 128
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\edas\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 128;
const int16_T B[128] = {
      -37,    -13,    -15,    -16,    -16,    -15,    -13,    -10,     -6,
       -1,      6,     14,     22,     32,     42,     51,     61,     69,
       77,     82,     85,     84,     81,     74,     63,     48,     28,
        5,    -21,    -51,    -82,   -116,   -149,   -182,   -212,   -239,
     -261,   -276,   -284,   -282,   -270,   -247,   -211,   -163,   -102,
      -27,     59,    158,    267,    385,    512,    643,    778,    914,
     1049,   1179,   1303,   1418,   1521,   1611,   1685,   1742,   1781,
     1801,   1801,   1781,   1742,   1685,   1611,   1521,   1418,   1303,
     1179,   1049,    914,    778,    643,    512,    385,    267,    158,
       59,    -27,   -102,   -163,   -211,   -247,   -270,   -282,   -284,
     -276,   -261,   -239,   -212,   -182,   -149,   -116,    -82,    -51,
      -21,      5,     28,     48,     63,     74,     81,     84,     85,
       82,     77,     69,     61,     51,     42,     32,     22,     14,
        6,     -1,     -6,    -10,    -13,    -15,    -16,    -16,    -15,
      -13,    -37
};
