
set_property PACKAGE_PIN D15 [get_ports SYS_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports SYS_CLK]
create_clock -period 40.000 -name SYS_CLK [get_ports SYS_CLK]

set_property PACKAGE_PIN A15 [get_ports {RF_CTRL_IN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RF_CTRL_IN[0]}]
#	AD9361-ctrl
set_property PACKAGE_PIN B15 [get_ports {RF_CTRL_IN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RF_CTRL_IN[1]}]
#	AD9361-ctrl
set_property PACKAGE_PIN A14 [get_ports {RF_CTRL_IN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RF_CTRL_IN[2]}]
#	AD9361-ctrl
set_property PACKAGE_PIN B14 [get_ports {RF_CTRL_IN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RF_CTRL_IN[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports PA_EN]
set_property PACKAGE_PIN AE11 [get_ports PA_EN]

set_property IOSTANDARD LVCMOS33 [get_ports RF_SW]
set_property PACKAGE_PIN AE10 [get_ports RF_SW]


set_property PACKAGE_PIN K2 [get_ports {TEST_LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_LED[0]}]
set_property PACKAGE_PIN K1 [get_ports {TEST_LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_LED[1]}]
set_property PACKAGE_PIN H2 [get_ports {TEST_LED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_LED[2]}]
set_property PACKAGE_PIN G1 [get_ports {TEST_LED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_LED[3]}]

set_property PACKAGE_PIN F10 [get_ports SPI_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_CLK]

set_property PACKAGE_PIN B6 [get_ports SPI_ENB]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_ENB]

set_property PACKAGE_PIN H7 [get_ports SPI_DI]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_DI]

set_property PACKAGE_PIN B12 [get_ports SPI_DO]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_DO]

set_property PACKAGE_PIN C11 [get_ports AD9361_RST]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_RST]

set_property PACKAGE_PIN A5 [get_ports AD9361_EN]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_EN]

set_property PACKAGE_PIN H6 [get_ports AD9361_Tx_Rx]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_Tx_Rx]

set_property PACKAGE_PIN E10 [get_ports AD9361_EN_AGC]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_EN_AGC]

set_property IOSTANDARD LVDS [get_ports AD9361_TX_Frame_P]
set_property PACKAGE_PIN D5 [get_ports AD9361_TX_Frame_N]
set_property IOSTANDARD LVDS [get_ports AD9361_TX_Frame_N]

set_property IOSTANDARD LVDS [get_ports AD9361_FB_CLK_P]
set_property PACKAGE_PIN G5 [get_ports AD9361_FB_CLK_N]
set_property IOSTANDARD LVDS [get_ports AD9361_FB_CLK_N]

set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[0]}]
set_property PACKAGE_PIN D8 [get_ports {AD9361_TX_DATA_N[0]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[0]}]

set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[1]}]
set_property PACKAGE_PIN E8 [get_ports {AD9361_TX_DATA_N[1]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[1]}]

set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[2]}]
set_property PACKAGE_PIN A7 [get_ports {AD9361_TX_DATA_N[2]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[2]}]

set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[3]}]
set_property PACKAGE_PIN A8 [get_ports {AD9361_TX_DATA_N[3]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[3]}]

set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[4]}]
set_property PACKAGE_PIN B9 [get_ports {AD9361_TX_DATA_N[4]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[4]}]

set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[5]}]
set_property PACKAGE_PIN A10 [get_ports {AD9361_TX_DATA_N[5]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[5]}]

set_property IOSTANDARD LVDS [get_ports AD9361_RX_Frame_P]
set_property DIFF_TERM TRUE [get_ports AD9361_RX_Frame_P]
set_property PACKAGE_PIN C6 [get_ports AD9361_RX_Frame_N]
set_property IOSTANDARD LVDS [get_ports AD9361_RX_Frame_N]
set_property DIFF_TERM TRUE [get_ports AD9361_RX_Frame_N]

set_property IOSTANDARD LVDS [get_ports AD9361_DATA_CLK_P]
set_property PACKAGE_PIN C7 [get_ports AD9361_DATA_CLK_N]
set_property IOSTANDARD LVDS [get_ports AD9361_DATA_CLK_N]

set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[0]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[0]}]
set_property PACKAGE_PIN F5 [get_ports {AD9361_RX_DATA_P[0]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[0]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[0]}]

set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[1]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[1]}]
set_property PACKAGE_PIN A4 [get_ports {AD9361_RX_DATA_P[1]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[1]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[1]}]

set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[2]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[2]}]
set_property PACKAGE_PIN C4 [get_ports {AD9361_RX_DATA_P[2]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[2]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[2]}]

set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[3]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[3]}]
set_property PACKAGE_PIN C2 [get_ports {AD9361_RX_DATA_P[3]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[3]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[3]}]

set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[4]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[4]}]
set_property PACKAGE_PIN B2 [get_ports {AD9361_RX_DATA_P[4]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[4]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[4]}]

set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[5]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[5]}]
set_property PACKAGE_PIN B5 [get_ports {AD9361_RX_DATA_P[5]}]
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[5]}]
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[5]}]

create_clock -period 6.667 -name AD9361_DATA_CLK_P [get_ports AD9361_DATA_CLK_P]
create_clock -period 6.667 -name AD9361_DATA_CLK_N [get_ports AD9361_DATA_CLK_N]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_P] -max 1.250 [get_ports {AD9361_RX_DATA_P[0] AD9361_RX_DATA_P[1] AD9361_RX_DATA_P[2] AD9361_RX_DATA_P[3] AD9361_RX_DATA_P[4] AD9361_RX_DATA_P[5] AD9361_RX_Frame_P}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_P] -clock_fall -max -add_delay 1.250 [get_ports {AD9361_RX_DATA_P[0] AD9361_RX_DATA_P[1] AD9361_RX_DATA_P[2] AD9361_RX_DATA_P[3] AD9361_RX_DATA_P[4] AD9361_RX_DATA_P[5] AD9361_RX_Frame_P}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_P] -min 0.250 [get_ports {AD9361_RX_DATA_P[0] AD9361_RX_DATA_P[1] AD9361_RX_DATA_P[2] AD9361_RX_DATA_P[3] AD9361_RX_DATA_P[4] AD9361_RX_DATA_P[5] AD9361_RX_Frame_P}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_P] -clock_fall -min -add_delay 0.250 [get_ports {AD9361_RX_DATA_P[0] AD9361_RX_DATA_P[1] AD9361_RX_DATA_P[2] AD9361_RX_DATA_P[3] AD9361_RX_DATA_P[4] AD9361_RX_DATA_P[5] AD9361_RX_Frame_P}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_N] -max 1.250 [get_ports {AD9361_DATA_CLK_N[0] AD9361_DATA_CLK_N[1] AD9361_DATA_CLK_N[2] AD9361_DATA_CLK_N[3] AD9361_DATA_CLK_N[4] AD9361_DATA_CLK_N[5] AD9361_RX_Frame_N}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_N] -clock_fall -max -add_delay 1.250 [get_ports {AD9361_DATA_CLK_N[0] AD9361_DATA_CLK_N[1] AD9361_DATA_CLK_N[2] AD9361_DATA_CLK_N[3] AD9361_DATA_CLK_N[4] AD9361_DATA_CLK_N[5] AD9361_RX_Frame_N}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_N] -min 0.250 [get_ports {AD9361_DATA_CLK_N[0] AD9361_DATA_CLK_N[1] AD9361_DATA_CLK_N[2] AD9361_DATA_CLK_N[3] AD9361_DATA_CLK_N[4] AD9361_DATA_CLK_N[5] AD9361_RX_Frame_N}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_N] -clock_fall -min -add_delay 0.250 [get_ports {AD9361_DATA_CLK_N[0] AD9361_DATA_CLK_N[1] AD9361_DATA_CLK_N[2] AD9361_DATA_CLK_N[3] AD9361_DATA_CLK_N[4] AD9361_DATA_CLK_N[5] AD9361_RX_Frame_N}]


# GMII

# GMII_GTXCLK
set_property PACKAGE_PIN AC23 [get_ports GMII_GTXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports GMII_GTXCLK]
# GMII_TXCLK
set_property PACKAGE_PIN AD23 [get_ports GMII_TXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports GMII_TXCLK]
# GMII_TX_EN
set_property PACKAGE_PIN AE22 [get_ports GMII_TX_EN]
set_property IOSTANDARD LVCMOS33 [get_ports GMII_TX_EN]
# GMII_TX_ER
set_property PACKAGE_PIN AF22 [get_ports GMII_TX_ER]
set_property IOSTANDARD LVCMOS33 [get_ports GMII_TX_ER]
# GMII_TXD[0..7]
set_property PACKAGE_PIN AF23 [get_ports {GMII_TXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_TXD[0]}]
set_property PACKAGE_PIN AE23 [get_ports {GMII_TXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_TXD[1]}]
set_property PACKAGE_PIN AF24 [get_ports {GMII_TXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_TXD[2]}]
set_property PACKAGE_PIN AF25 [get_ports {GMII_TXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_TXD[3]}]
set_property PACKAGE_PIN AE25 [get_ports {GMII_TXD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_TXD[4]}]
set_property PACKAGE_PIN AE26 [get_ports {GMII_TXD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_TXD[5]}]
set_property PACKAGE_PIN AD25 [get_ports {GMII_TXD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_TXD[6]}]
set_property PACKAGE_PIN AD26 [get_ports {GMII_TXD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_TXD[7]}]
# GMII_RXCLK
set_property PACKAGE_PIN AD20 [get_ports GMII_RXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports GMII_RXCLK]
# GMII_RX_DV
set_property PACKAGE_PIN AB25 [get_ports GMII_RX_DV]
set_property IOSTANDARD LVCMOS33 [get_ports GMII_RX_DV]
# GMII_RX_ER
set_property PACKAGE_PIN AC26 [get_ports GMII_RX_ER]
set_property IOSTANDARD LVCMOS33 [get_ports GMII_RX_ER]
# GMII_RXD[0..7]
set_property PACKAGE_PIN W20 [get_ports {GMII_RXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_RXD[0]}]
set_property PACKAGE_PIN Y20 [get_ports {GMII_RXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_RXD[1]}]
set_property PACKAGE_PIN AA25 [get_ports {GMII_RXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_RXD[2]}]
set_property PACKAGE_PIN AA23 [get_ports {GMII_RXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_RXD[3]}]
set_property PACKAGE_PIN AA22 [get_ports {GMII_RXD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_RXD[4]}]
set_property PACKAGE_PIN AB22 [get_ports {GMII_RXD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_RXD[5]}]
set_property PACKAGE_PIN AB21 [get_ports {GMII_RXD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_RXD[6]}]
set_property PACKAGE_PIN AB26 [get_ports {GMII_RXD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GMII_RXD[7]}]
# GMII_MDIO_MDC
set_property PACKAGE_PIN AB24 [get_ports GMII_MDIO_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports GMII_MDIO_MDC]
# GMII_MDIO
set_property PACKAGE_PIN AF18 [get_ports GMII_MDIO]
set_property IOSTANDARD LVCMOS33 [get_ports GMII_MDIO]
# GMII_GE_IND
set_property PACKAGE_PIN AA24 [get_ports GMII_GE_IND]
set_property IOSTANDARD LVCMOS33 [get_ports GMII_GE_IND]


set_property MARK_DEBUG true [get_nets {AXI_HP0_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {AXI_HP0_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {AXI_HP0_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {AXI_HP0_awaddr[4]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[19]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[17]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[31]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[18]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[16]}]
connect_debug_port u_ila_1/probe0 [get_nets [list a2s_wea]]
connect_debug_port u_ila_1/probe10 [get_nets [list ca2s/a2s_addr0]]
connect_debug_port u_ila_1/probe11 [get_nets [list cs2a/s2a_addr0]]

set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[9]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[16]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[18]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[15]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[31]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[14]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[17]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[11]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[7]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[8]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[6]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[12]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[19]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[13]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_awaddr[10]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[14]}]
set_property MARK_DEBUG false [get_nets n_0_0]
set_property MARK_DEBUG false [get_nets n_0_5]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[13]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[11]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[10]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[8]}]
set_property MARK_DEBUG false [get_nets n_0_2]
set_property MARK_DEBUG false [get_nets n_0_11]
set_property MARK_DEBUG false [get_nets n_0_4]
set_property MARK_DEBUG false [get_nets n_0_7]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[6]}]
set_property MARK_DEBUG false [get_nets n_0_8]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[15]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[7]}]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[12]}]
set_property MARK_DEBUG false [get_nets n_0_6]
set_property MARK_DEBUG false [get_nets n_0_10]
set_property MARK_DEBUG false [get_nets {AXI_HP0_araddr[9]}]
set_property MARK_DEBUG false [get_nets n_0_9]
set_property MARK_DEBUG false [get_nets n_0_3]
set_property MARK_DEBUG false [get_nets n_0_1]

set_property MARK_DEBUG false [get_nets n_0_12]
set_property MARK_DEBUG false [get_nets n_0_15]
set_property MARK_DEBUG false [get_nets n_0_14]
set_property MARK_DEBUG false [get_nets n_0_20]
set_property MARK_DEBUG false [get_nets n_0_17]
set_property MARK_DEBUG false [get_nets n_0_16]
set_property MARK_DEBUG false [get_nets n_0_13]
set_property MARK_DEBUG false [get_nets n_0_19]
set_property MARK_DEBUG false [get_nets n_0_21]
set_property MARK_DEBUG false [get_nets n_0_18]



set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[9]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[12]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[16]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[18]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[22]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[23]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[10]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[19]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[25]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[8]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[29]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[20]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[26]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[21]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[1]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[17]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[11]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[28]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[30]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[13]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[15]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[31]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[24]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[27]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_awaddr[14]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[15]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[13]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[11]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[19]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[12]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[18]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[26]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[16]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[14]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[7]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[20]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[29]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[30]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[31]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[27]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[25]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[22]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[10]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[9]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[8]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[0]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[2]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[4]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[6]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[21]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[23]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[24]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[28]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[5]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[17]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[3]}]
set_property MARK_DEBUG true [get_nets {core/armocm_i/S_AXI_HP0_araddr[1]}]

create_debug_core u_ila_0_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0_0]
set_property port_width 1 [get_debug_ports u_ila_0_0/clk]
connect_debug_port u_ila_0_0/clk [get_nets [list AXI_clk]]
set_property port_width 5 [get_debug_ports u_ila_0_0/probe0]
connect_debug_port u_ila_0_0/probe0 [get_nets [list {a2s/a2s_addr[0]} {a2s/a2s_addr[1]} {a2s/a2s_addr[2]} {a2s/a2s_addr[3]} {a2s/a2s_addr[4]}]]
create_debug_core u_ila_1_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1_0]
set_property port_width 1 [get_debug_ports u_ila_1_0/clk]
connect_debug_port u_ila_1_0/clk [get_nets [list SYS_CLK_BUFG]]
set_property port_width 5 [get_debug_ports u_ila_1_0/probe0]
connect_debug_port u_ila_1_0/probe0 [get_nets [list {a2s/Iaddr[0]} {a2s/Iaddr[1]} {a2s/Iaddr[2]} {a2s/Iaddr[3]} {a2s/Iaddr[4]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 5 [get_debug_ports u_ila_0_0/probe1]
connect_debug_port u_ila_0_0/probe1 [get_nets [list {a2s/s2a_addr[0]} {a2s/s2a_addr[1]} {a2s/s2a_addr[2]} {a2s/s2a_addr[3]} {a2s/s2a_addr[4]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 32 [get_debug_ports u_ila_0_0/probe2]
connect_debug_port u_ila_0_0/probe2 [get_nets [list {core/armocm_i/S_AXI_HP0_araddr[0]} {core/armocm_i/S_AXI_HP0_araddr[1]} {core/armocm_i/S_AXI_HP0_araddr[2]} {core/armocm_i/S_AXI_HP0_araddr[3]} {core/armocm_i/S_AXI_HP0_araddr[4]} {core/armocm_i/S_AXI_HP0_araddr[5]} {core/armocm_i/S_AXI_HP0_araddr[6]} {core/armocm_i/S_AXI_HP0_araddr[7]} {core/armocm_i/S_AXI_HP0_araddr[8]} {core/armocm_i/S_AXI_HP0_araddr[9]} {core/armocm_i/S_AXI_HP0_araddr[10]} {core/armocm_i/S_AXI_HP0_araddr[11]} {core/armocm_i/S_AXI_HP0_araddr[12]} {core/armocm_i/S_AXI_HP0_araddr[13]} {core/armocm_i/S_AXI_HP0_araddr[14]} {core/armocm_i/S_AXI_HP0_araddr[15]} {core/armocm_i/S_AXI_HP0_araddr[16]} {core/armocm_i/S_AXI_HP0_araddr[17]} {core/armocm_i/S_AXI_HP0_araddr[18]} {core/armocm_i/S_AXI_HP0_araddr[19]} {core/armocm_i/S_AXI_HP0_araddr[20]} {core/armocm_i/S_AXI_HP0_araddr[21]} {core/armocm_i/S_AXI_HP0_araddr[22]} {core/armocm_i/S_AXI_HP0_araddr[23]} {core/armocm_i/S_AXI_HP0_araddr[24]} {core/armocm_i/S_AXI_HP0_araddr[25]} {core/armocm_i/S_AXI_HP0_araddr[26]} {core/armocm_i/S_AXI_HP0_araddr[27]} {core/armocm_i/S_AXI_HP0_araddr[28]} {core/armocm_i/S_AXI_HP0_araddr[29]} {core/armocm_i/S_AXI_HP0_araddr[30]} {core/armocm_i/S_AXI_HP0_araddr[31]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 32 [get_debug_ports u_ila_0_0/probe3]
connect_debug_port u_ila_0_0/probe3 [get_nets [list {core/armocm_i/S_AXI_HP0_awaddr[0]} {core/armocm_i/S_AXI_HP0_awaddr[1]} {core/armocm_i/S_AXI_HP0_awaddr[2]} {core/armocm_i/S_AXI_HP0_awaddr[3]} {core/armocm_i/S_AXI_HP0_awaddr[4]} {core/armocm_i/S_AXI_HP0_awaddr[5]} {core/armocm_i/S_AXI_HP0_awaddr[6]} {core/armocm_i/S_AXI_HP0_awaddr[7]} {core/armocm_i/S_AXI_HP0_awaddr[8]} {core/armocm_i/S_AXI_HP0_awaddr[9]} {core/armocm_i/S_AXI_HP0_awaddr[10]} {core/armocm_i/S_AXI_HP0_awaddr[11]} {core/armocm_i/S_AXI_HP0_awaddr[12]} {core/armocm_i/S_AXI_HP0_awaddr[13]} {core/armocm_i/S_AXI_HP0_awaddr[14]} {core/armocm_i/S_AXI_HP0_awaddr[15]} {core/armocm_i/S_AXI_HP0_awaddr[16]} {core/armocm_i/S_AXI_HP0_awaddr[17]} {core/armocm_i/S_AXI_HP0_awaddr[18]} {core/armocm_i/S_AXI_HP0_awaddr[19]} {core/armocm_i/S_AXI_HP0_awaddr[20]} {core/armocm_i/S_AXI_HP0_awaddr[21]} {core/armocm_i/S_AXI_HP0_awaddr[22]} {core/armocm_i/S_AXI_HP0_awaddr[23]} {core/armocm_i/S_AXI_HP0_awaddr[24]} {core/armocm_i/S_AXI_HP0_awaddr[25]} {core/armocm_i/S_AXI_HP0_awaddr[26]} {core/armocm_i/S_AXI_HP0_awaddr[27]} {core/armocm_i/S_AXI_HP0_awaddr[28]} {core/armocm_i/S_AXI_HP0_awaddr[29]} {core/armocm_i/S_AXI_HP0_awaddr[30]} {core/armocm_i/S_AXI_HP0_awaddr[31]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 10 [get_debug_ports u_ila_0_0/probe4]
connect_debug_port u_ila_0_0/probe4 [get_nets [list {AXI_HP0_araddr[6]} {AXI_HP0_araddr[7]} {AXI_HP0_araddr[8]} {AXI_HP0_araddr[9]} {AXI_HP0_araddr[10]} {AXI_HP0_araddr[11]} {AXI_HP0_araddr[12]} {AXI_HP0_araddr[13]} {AXI_HP0_araddr[14]} {AXI_HP0_araddr[15]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 10 [get_debug_ports u_ila_0_0/probe5]
connect_debug_port u_ila_0_0/probe5 [get_nets [list {AXI_HP0_awaddr[6]} {AXI_HP0_awaddr[7]} {AXI_HP0_awaddr[8]} {AXI_HP0_awaddr[9]} {AXI_HP0_awaddr[10]} {AXI_HP0_awaddr[11]} {AXI_HP0_awaddr[12]} {AXI_HP0_awaddr[13]} {AXI_HP0_awaddr[14]} {AXI_HP0_awaddr[15]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 32 [get_debug_ports u_ila_0_0/probe6]
connect_debug_port u_ila_0_0/probe6 [get_nets [list {AXI_HP0_rdata[0]} {AXI_HP0_rdata[1]} {AXI_HP0_rdata[2]} {AXI_HP0_rdata[3]} {AXI_HP0_rdata[4]} {AXI_HP0_rdata[5]} {AXI_HP0_rdata[6]} {AXI_HP0_rdata[7]} {AXI_HP0_rdata[8]} {AXI_HP0_rdata[9]} {AXI_HP0_rdata[10]} {AXI_HP0_rdata[11]} {AXI_HP0_rdata[12]} {AXI_HP0_rdata[13]} {AXI_HP0_rdata[14]} {AXI_HP0_rdata[15]} {AXI_HP0_rdata[16]} {AXI_HP0_rdata[17]} {AXI_HP0_rdata[18]} {AXI_HP0_rdata[19]} {AXI_HP0_rdata[20]} {AXI_HP0_rdata[21]} {AXI_HP0_rdata[22]} {AXI_HP0_rdata[23]} {AXI_HP0_rdata[24]} {AXI_HP0_rdata[25]} {AXI_HP0_rdata[26]} {AXI_HP0_rdata[27]} {AXI_HP0_rdata[28]} {AXI_HP0_rdata[29]} {AXI_HP0_rdata[30]} {AXI_HP0_rdata[31]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 32 [get_debug_ports u_ila_0_0/probe7]
connect_debug_port u_ila_0_0/probe7 [get_nets [list {AXI_HP0_wdata[0]} {AXI_HP0_wdata[1]} {AXI_HP0_wdata[2]} {AXI_HP0_wdata[3]} {AXI_HP0_wdata[4]} {AXI_HP0_wdata[5]} {AXI_HP0_wdata[6]} {AXI_HP0_wdata[7]} {AXI_HP0_wdata[8]} {AXI_HP0_wdata[9]} {AXI_HP0_wdata[10]} {AXI_HP0_wdata[11]} {AXI_HP0_wdata[12]} {AXI_HP0_wdata[13]} {AXI_HP0_wdata[14]} {AXI_HP0_wdata[15]} {AXI_HP0_wdata[16]} {AXI_HP0_wdata[17]} {AXI_HP0_wdata[18]} {AXI_HP0_wdata[19]} {AXI_HP0_wdata[20]} {AXI_HP0_wdata[21]} {AXI_HP0_wdata[22]} {AXI_HP0_wdata[23]} {AXI_HP0_wdata[24]} {AXI_HP0_wdata[25]} {AXI_HP0_wdata[26]} {AXI_HP0_wdata[27]} {AXI_HP0_wdata[28]} {AXI_HP0_wdata[29]} {AXI_HP0_wdata[30]} {AXI_HP0_wdata[31]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe8]
connect_debug_port u_ila_0_0/probe8 [get_nets [list a2s/a2s_wea]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe9]
connect_debug_port u_ila_0_0/probe9 [get_nets [list AXI_HP0_arready]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe10]
connect_debug_port u_ila_0_0/probe10 [get_nets [list AXI_HP0_arvalid]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe11]
connect_debug_port u_ila_0_0/probe11 [get_nets [list AXI_HP0_awready]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe12]
connect_debug_port u_ila_0_0/probe12 [get_nets [list AXI_HP0_awvalid]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe13]
connect_debug_port u_ila_0_0/probe13 [get_nets [list AXI_HP0_rready]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe14]
connect_debug_port u_ila_0_0/probe14 [get_nets [list AXI_HP0_rvalid]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe15]
connect_debug_port u_ila_0_0/probe15 [get_nets [list AXI_HP0_wlast]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe16]
connect_debug_port u_ila_0_0/probe16 [get_nets [list AXI_HP0_wready]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe17]
connect_debug_port u_ila_0_0/probe17 [get_nets [list AXI_HP0_wvalid]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe18]
connect_debug_port u_ila_0_0/probe18 [get_nets [list a2s/s2a_en]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe19]
connect_debug_port u_ila_0_0/probe19 [get_nets [list AXI_HP0_rlast]]
create_debug_port u_ila_1_0 probe
set_property port_width 5 [get_debug_ports u_ila_1_0/probe1]
connect_debug_port u_ila_1_0/probe1 [get_nets [list {a2s/Oaddr[0]} {a2s/Oaddr[1]} {a2s/Oaddr[2]} {a2s/Oaddr[3]} {a2s/Oaddr[4]}]]
create_debug_port u_ila_1_0 probe
set_property port_width 32 [get_debug_ports u_ila_1_0/probe2]
connect_debug_port u_ila_1_0/probe2 [get_nets [list {Sin[0]} {Sin[1]} {Sin[2]} {Sin[3]} {Sin[4]} {Sin[5]} {Sin[6]} {Sin[7]} {Sin[8]} {Sin[9]} {Sin[10]} {Sin[11]} {Sin[12]} {Sin[13]} {Sin[14]} {Sin[15]} {Sin[16]} {Sin[17]} {Sin[18]} {Sin[19]} {Sin[20]} {Sin[21]} {Sin[22]} {Sin[23]} {Sin[24]} {Sin[25]} {Sin[26]} {Sin[27]} {Sin[28]} {Sin[29]} {Sin[30]} {Sin[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets AXI_clk]
